from __future__ import annotations

from typing import Any, Protocol


class SupportRepository(Protocol):
    async def health(self) -> None: ...
    async def close(self) -> None: ...
    async def create_operator_session(self, session: dict[str, str]) -> None: ...
    async def get_operator_session(self, session_hash: str) -> dict[str, str] | None: ...
    async def delete_operator_session(self, session_hash: str) -> None: ...
    async def consume_login_attempt(
        self, key: str, window_seconds: int, max_attempts: int
    ) -> dict[str, Any]: ...
    async def clear_login_attempts(self, key: str) -> None: ...
    async def get_ticket(self, ticket_id: str) -> dict[str, Any] | None: ...
    async def get_customer(self, customer_id: str) -> dict[str, Any] | None: ...
    async def list_customer_invoices(self, customer_id: str) -> list[dict[str, Any]]: ...
    async def list_policies(self) -> list[dict[str, Any]]: ...
    async def list_tickets(self, status: str | None = None) -> list[dict[str, Any]]: ...
    async def get_ticket_context(
        self, ticket_id: str, policy_hits: list[dict[str, Any]]
    ) -> dict[str, Any]: ...
    async def create_ticket(self, input_data: dict[str, Any]) -> dict[str, Any]: ...
    async def create_refund_proposal(self, input_data: dict[str, Any]) -> dict[str, Any]: ...
    async def decide_refund_proposal(self, input_data: dict[str, Any]) -> dict[str, Any]: ...
    async def execute_refund_proposal(self, input_data: dict[str, Any]) -> dict[str, Any]: ...


def ticket_triage_source(repository: SupportRepository) -> SupportRepository:
    return repository
